/**
 * Built-in default configurations (AH-0MTZWZ9TE009CVUA).
 *
 * Leaf module (imports only `constants`) so the CSV codec and the Vite
 * plugin can use the defaults without pulling in `configStore.ts` (whose
 * `?raw` CSV imports would break the Vite config loader). The committed CSV
 * files are the runtime source of truth; these are the fallback values.
 */

import {
  GAME_WIDTH,
  GAME_HEIGHT,
  THRUST_ACCELERATION,
  MAX_SPEED,
  SHIP_SIZE,
  THRUST_FLAME_LENGTH,
  SHIP_COLOR,
  THRUST_FLAME_COLOR,
  THRUST_FLAME_INNER_COLOR,
  FRICTION_DECELERATION,
} from './constants';
import type { EnemyConfig, ShipConfig } from './configTypes';

/** Seed enemy archetypes — the fallback when the CSV cannot be read. */
export const DEFAULT_ENEMY_CONFIGS: Record<string, EnemyConfig> = {
  scout: {
    key: 'scout',
    displayName: 'Scout',
    formationKind: 'v',
    count: 6,
    spacingX: 26,
    spacingY: 22,
    driftSpeed: 40,
    startX: GAME_WIDTH * 0.25,
    startY: GAME_HEIGHT * 0.5,
    size: 16,
    color: 0x00ff00,
    bulletColor: 0xff4444,
    bulletSize: 3,
    shotPattern: 'aimed',
    fireInterval: 1200,
    bulletSpeed: 200,
    bulletLifetime: 1.5,
    burstCount: 1,
    shotProbability: 1.0,
  },
  diver: {
    key: 'diver',
    displayName: 'Diver',
    formationKind: 'diver',
    count: 6,
    spacingX: 30,
    spacingY: 25,
    driftSpeed: 30,
    startX: GAME_WIDTH * 0.25,
    startY: GAME_HEIGHT * 0.45,
    size: 18,
    color: 0xffff00,
    bulletColor: 0xffee88,
    bulletSize: 3,
    shotPattern: 'spread',
    fireInterval: 1000,
    bulletSpeed: 220,
    bulletLifetime: 1.5,
    burstCount: 4,
    shotProbability: 1.0,
  },
  tank: {
    key: 'tank',
    displayName: 'Tank',
    formationKind: 'rect',
    count: 6,
    spacingX: 50,
    spacingY: 45,
    driftSpeed: 18,
    startX: GAME_WIDTH * 0.25,
    startY: GAME_HEIGHT * 0.5,
    size: 28,
    color: 0xff6600,
    bulletColor: 0xffaa00,
    bulletSize: 4,
    shotPattern: 'radial',
    fireInterval: 2400,
    bulletSpeed: 150,
    bulletLifetime: 2.0,
    burstCount: 10,
    shotProbability: 1.0,
  },
  phaser: {
    key: 'phaser',
    displayName: 'Phaser',
    formationKind: 'orbital',
    count: 4,
    spacingX: 80,
    spacingY: 80,
    driftSpeed: 30,
    startX: GAME_WIDTH * 0.35,
    startY: GAME_HEIGHT * 0.5,
    size: 14,
    color: 0xff00ff,
    bulletColor: 0xff4444,
    bulletSize: 3,
    shotPattern: 'radial',
    fireInterval: 2000,
    bulletSpeed: 180,
    bulletLifetime: 1.75,
    burstCount: 8,
    shotProbability: 1.0,
  },
  swarm: {
    key: 'swarm',
    displayName: 'Swarm',
    formationKind: 'swarm',
    count: 15,
    spacingX: 28,
    spacingY: 24,
    driftSpeed: 60,
    startX: GAME_WIDTH * 0.15,
    startY: GAME_HEIGHT * 0.3,
    size: 15,
    color: 0x0066ff,
    bulletColor: 0x00ccff,
    bulletSize: 3,
    shotPattern: 'coordinated',
    fireInterval: 900,
    bulletSpeed: 180,
    bulletLifetime: 1.5,
    burstCount: 1,
    // Only a quarter of the 15-member cluster fires per cycle.
    shotProbability: 0.25,
  },
  boss: {
    key: 'boss',
    // Plain single-enemy archetype — NOT the multi-phase Central AI.
    displayName: 'Boss Swarm',
    formationKind: 'single',
    count: 1,
    spacingX: 0,
    spacingY: 0,
    driftSpeed: 0,
    startX: GAME_WIDTH / 2,
    startY: GAME_HEIGHT / 2 - 100,
    size: 50,
    color: 0xff0000,
    bulletColor: 0xffffff,
    bulletSize: 4,
    shotPattern: 'radial',
    fireInterval: 1200,
    bulletSpeed: 160,
    bulletLifetime: 2.0,
    burstCount: 8,
    shotProbability: 1.0,
  },
  asteroid: {
    key: 'asteroid',
    displayName: 'Asteroid',
    formationKind: 'single',
    count: 1,
    spacingX: 0,
    spacingY: 0,
    driftSpeed: 0,
    startX: GAME_WIDTH * 0.5,
    startY: GAME_HEIGHT * 0.3,
    size: 42,
    color: 0x888888,
    bulletColor: 0x888888,
    bulletSize: 3,
    shotPattern: 'none',
    fireInterval: 1000,
    bulletSpeed: 100,
    bulletLifetime: 1.5,
    burstCount: 1,
    shotProbability: 1.0,
  },
};

export const DEFAULT_ENEMY_KEYS = Object.keys(DEFAULT_ENEMY_CONFIGS);

/** Built-in ship defaults — sourced from the leaf `constants.ts` values. */
export const DEFAULT_CONFIG: ShipConfig = {
  thrustAcceleration: THRUST_ACCELERATION,
  maxSpeed: MAX_SPEED,
  shipSize: SHIP_SIZE,
  thrustFlameLength: THRUST_FLAME_LENGTH,
  shipColor: SHIP_COLOR,
  thrustFlameColor: THRUST_FLAME_COLOR,
  thrustFlameInnerColor: THRUST_FLAME_INNER_COLOR,
  frictionDeceleration: FRICTION_DECELERATION,
  controlScheme: 'fourDirectional',
  asteroidsRotationSpeed: 3,
};
