/**
 * Built-in default configurations (AH-0MTZWZ9TE009CVUA).
 *
 * Leaf module (imports only `constants`) so the CSV codec and the Vite
 * plugin can use the defaults without pulling in `configStore.ts` (whose
 * `?raw` CSV imports would break the Vite config loader). The committed CSV
 * files are the runtime source of truth; these are the fallback values.
 */

import {
  GAME_WIDTH,
  GAME_HEIGHT,
  THRUST_ACCELERATION,
  MAX_SPEED,
  SHIP_SIZE,
  THRUST_FLAME_LENGTH,
  SHIP_COLOR,
  THRUST_FLAME_COLOR,
  THRUST_FLAME_INNER_COLOR,
  FRICTION_DECELERATION,
} from './constants';
import type { EnemyConfig, ShipConfig } from './configTypes';

/** Seed enemy archetypes — the fallback when the CSV cannot be read. */
export const DEFAULT_ENEMY_CONFIGS: Record<string, EnemyConfig> = {
  scout: {
    key: 'scout',
    displayName: 'Scout',
    formationKind: 'v',
    count: 6,
    spacingX: 26,
    spacingY: 22,
    driftSpeed: 40,
    startX: GAME_WIDTH * 0.25,
    startY: GAME_HEIGHT * 0.5,
    startXMin: GAME_WIDTH * 0.25,
    startXMax: GAME_WIDTH * 0.25,
    startYMin: GAME_HEIGHT * 0.5,
    startYMax: GAME_HEIGHT * 0.5,
    size: 16,
    health: 1,
    color: 0x00ff00,
    bulletColor: 0xff4444,
    bulletSize: 3,
    shotPattern: 'aimed',
    fireInterval: 1200,
    bulletSpeed: 100,
    bulletLifetime: 1.5,
    burstCount: 1,
    shotProbability: 1.0,
  },
  diver: {
    key: 'diver',
    displayName: 'Diver',
    formationKind: 'diver',
    count: 6,
    spacingX: 30,
    spacingY: 25,
    driftSpeed: 30,
    startX: GAME_WIDTH * 0.25,
    startY: GAME_HEIGHT * 0.45,
    startXMin: GAME_WIDTH * 0.25,
    startXMax: GAME_WIDTH * 0.25,
    startYMin: GAME_HEIGHT * 0.45,
    startYMax: GAME_HEIGHT * 0.45,
    size: 18,
    health: 1,
    color: 0xffff00,
    bulletColor: 0xffee88,
    bulletSize: 3,
    shotPattern: 'spread',
    fireInterval: 1000,
    bulletSpeed: 110,
    bulletLifetime: 1.5,
    burstCount: 4,
    shotProbability: 1.0,
  },
  tank: {
    key: 'tank',
    displayName: 'Tank',
    formationKind: 'rect',
    count: 6,
    spacingX: 50,
    spacingY: 45,
    driftSpeed: 18,
    startX: GAME_WIDTH * 0.25,
    startY: GAME_HEIGHT * 0.5,
    startXMin: GAME_WIDTH * 0.25,
    startXMax: GAME_WIDTH * 0.25,
    startYMin: GAME_HEIGHT * 0.5,
    startYMax: GAME_HEIGHT * 0.5,
    size: 28,
    health: 1,
    color: 0xff6600,
    bulletColor: 0xffaa00,
    bulletSize: 4,
    shotPattern: 'radial',
    fireInterval: 2400,
    bulletSpeed: 75,
    bulletLifetime: 2.0,
    burstCount: 10,
    shotProbability: 1.0,
  },
  phaser: {
    key: 'phaser',
    displayName: 'Phaser',
    formationKind: 'orbital',
    count: 4,
    spacingX: 80,
    spacingY: 80,
    driftSpeed: 30,
    startX: GAME_WIDTH * 0.35,
    startY: GAME_HEIGHT * 0.5,
    startXMin: GAME_WIDTH * 0.35,
    startXMax: GAME_WIDTH * 0.35,
    startYMin: GAME_HEIGHT * 0.5,
    startYMax: GAME_HEIGHT * 0.5,
    size: 14,
    health: 1,
    color: 0xff00ff,
    bulletColor: 0xff4444,
    bulletSize: 3,
    shotPattern: 'radial',
    fireInterval: 2000,
    bulletSpeed: 90,
    bulletLifetime: 1.75,
    burstCount: 8,
    shotProbability: 1.0,
  },
  swarm: {
    key: 'swarm',
    displayName: 'Swarm',
    formationKind: 'swarm',
    count: 15,
    spacingX: 28,
    spacingY: 24,
    driftSpeed: 60,
    startX: GAME_WIDTH * 0.15,
    startY: GAME_HEIGHT * 0.3,
    startXMin: GAME_WIDTH * 0.15,
    startXMax: GAME_WIDTH * 0.15,
    startYMin: GAME_HEIGHT * 0.3,
    startYMax: GAME_HEIGHT * 0.3,
    size: 15,
    health: 1,
    color: 0x0066ff,
    bulletColor: 0x00ccff,
    bulletSize: 3,
    shotPattern: 'coordinated',
    fireInterval: 900,
    bulletSpeed: 90,
    bulletLifetime: 1.5,
    burstCount: 1,
    // Only a quarter of the 15-member cluster fires per cycle.
    shotProbability: 0.25,
  },
  boss: {
    key: 'boss',
    // Plain single-enemy archetype — NOT the multi-phase Central AI.
    displayName: 'Boss Swarm',
    formationKind: 'single',
    count: 1,
    spacingX: 0,
    spacingY: 0,
    driftSpeed: 0,
    startX: GAME_WIDTH / 2,
    startY: GAME_HEIGHT / 2 - 100,
    startXMin: GAME_WIDTH / 2,
    startXMax: GAME_WIDTH / 2,
    startYMin: GAME_HEIGHT / 2 - 100,
    startYMax: GAME_HEIGHT / 2 - 100,
    size: 50,
    health: 1,
    color: 0xff0000,
    bulletColor: 0xffffff,
    bulletSize: 4,
    shotPattern: 'radial',
    fireInterval: 1200,
    bulletSpeed: 80,
    bulletLifetime: 2.0,
    burstCount: 8,
    shotProbability: 1.0,
  },
  asteroid: {
    key: 'asteroid',
    displayName: 'Asteroid',
    formationKind: 'single',
    count: 1,
    spacingX: 0,
    spacingY: 0,
    driftSpeed: 0,
    startX: GAME_WIDTH * 0.5,
    startY: GAME_HEIGHT * 0.3,
    startXMin: GAME_WIDTH * 0.5,
    startXMax: GAME_WIDTH * 0.5,
    startYMin: GAME_HEIGHT * 0.3,
    startYMax: GAME_HEIGHT * 0.3,
    size: 42,
    health: 1,
    color: 0x888888,
    bulletColor: 0x888888,
    bulletSize: 3,
    shotPattern: 'none',
    fireInterval: 1000,
    bulletSpeed: 50,
    bulletLifetime: 1.5,
    burstCount: 1,
    shotProbability: 1.0,
  },
  // Space Invaders archetype (AH-0MV01EDZS0005R20): a rigid block that steps
  // horizontally, reverses at the arena edge, drops a row per reversal and
  // speeds up as it thins. `marchStep`/`marchDrop` are the neutral tuning
  // axes; `driftSpeed` is the reference px/s that sets the full-strength
  // step cadence (`marchStep / driftSpeed`).
  march: {
    key: 'march',
    displayName: 'Invader',
    formationKind: 'march',
    count: 11,
    spacingX: 26,
    spacingY: 24,
    driftSpeed: 20,
    marchStep: 20,
    marchDrop: 14,
    startX: GAME_WIDTH * 0.5,
    startY: GAME_HEIGHT * 0.25,
    startXMin: GAME_WIDTH * 0.5,
    startXMax: GAME_WIDTH * 0.5,
    startYMin: GAME_HEIGHT * 0.25,
    startYMax: GAME_HEIGHT * 0.25,
    size: 16,
    health: 1,
    color: 0x00ff66,
    bulletColor: 0xff4444,
    bulletSize: 3,
    shotPattern: 'aimed',
    fireInterval: 1400,
    bulletSpeed: 90,
    bulletLifetime: 1.4,
    burstCount: 1,
    shotProbability: 0.4,
  },
  // Galaga tractor-beam capturer (AH-0MV01EFII008298D): descends to the
  // player's row, projects a short-lived bounded tractor beam, then withdraws
  // and re-forms. `beamDuration`/`pullStrength` are the neutral tuning axes.
  capturer: {
    key: 'capturer',
    displayName: 'Capturer',
    formationKind: 'single',
    count: 1,
    spacingX: 0,
    spacingY: 0,
    driftSpeed: 0,
    startX: GAME_WIDTH * 0.5,
    startY: GAME_HEIGHT * 0.2,
    startXMin: GAME_WIDTH * 0.5,
    startXMax: GAME_WIDTH * 0.5,
    startYMin: GAME_HEIGHT * 0.2,
    startYMax: GAME_HEIGHT * 0.2,
    size: 18,
    health: 2,
    color: 0xff33cc,
    bulletColor: 0xff8888,
    bulletSize: 3,
    shotPattern: 'none',
    fireInterval: 1000,
    bulletSpeed: 50,
    bulletLifetime: 1,
    burstCount: 1,
    shotProbability: 0,
    beamDuration: 1800,
    pullStrength: 90,
  },
  // Robotron homing horde (AH-0MV01EKTL001NRE6): a dense pack of small, fast
  // non-firing grunts that pour in from the arena edges and home on the live
  // player with bounded steering. The horde is delivered by the dynamic
  // `HordeSpawner` in the game; the formation count is the horde size
  // (surfaced in the gym as density) and `driftSpeed` is the homing speed
  // (see `docs/CLASSIC_ENEMY_RESEARCH.md` §5). `hordeGroupSize` /
  // `hordeSpawnInterval` tune the timed edge spawns.
  grunt: {
    key: 'grunt',
    displayName: 'Grunt Horde',
    formationKind: 'swarm',
    count: 16,
    spacingX: 30,
    spacingY: 26,
    driftSpeed: 110,
    startX: GAME_WIDTH * 0.5,
    startY: GAME_HEIGHT * 0.35,
    startXMin: GAME_WIDTH * 0.5,
    startXMax: GAME_WIDTH * 0.5,
    startYMin: GAME_HEIGHT * 0.35,
    startYMax: GAME_HEIGHT * 0.35,
    size: 12,
    health: 1,
    color: 0xff00aa,
    bulletColor: 0xffffff,
    bulletSize: 3,
    shotPattern: 'none',
    fireInterval: 1000,
    bulletSpeed: 50,
    bulletLifetime: 1.5,
    burstCount: 1,
    shotProbability: 0,
    hordeGroupSize: 4,
    hordeSpawnInterval: 1.6,
  },
  // Pac-Man personality pursuers (AH-0MV01EH2U008XT3Q): four fast, low-HP
  // non-firing roamer-pursuers, one CSV row per personality so the gym can
  // exercise each independently. They move via the shared `Ghost` steering
  // policy (chase/ambush/flank/wander) and are threat-by-contact only.
  'ghost-chase': {
    key: 'ghost-chase',
    displayName: 'Ghost (Chase)',
    formationKind: 'single',
    count: 1,
    spacingX: 0,
    spacingY: 0,
    driftSpeed: 0,
    startX: GAME_WIDTH * 0.5,
    startY: GAME_HEIGHT * 0.25,
    startXMin: GAME_WIDTH * 0.5,
    startXMax: GAME_WIDTH * 0.5,
    startYMin: GAME_HEIGHT * 0.25,
    startYMax: GAME_HEIGHT * 0.25,
    size: 16,
    health: 1,
    color: 0xff2222,
    bulletColor: 0xffffff,
    bulletSize: 3,
    shotPattern: 'none',
    fireInterval: 1000,
    bulletSpeed: 50,
    bulletLifetime: 1.5,
    burstCount: 1,
    shotProbability: 0,
  },
  'ghost-ambush': {
    key: 'ghost-ambush',
    displayName: 'Ghost (Ambush)',
    formationKind: 'single',
    count: 1,
    spacingX: 0,
    spacingY: 0,
    driftSpeed: 0,
    startX: GAME_WIDTH * 0.5,
    startY: GAME_HEIGHT * 0.25,
    startXMin: GAME_WIDTH * 0.5,
    startXMax: GAME_WIDTH * 0.5,
    startYMin: GAME_HEIGHT * 0.25,
    startYMax: GAME_HEIGHT * 0.25,
    size: 16,
    health: 1,
    color: 0xffb8ff,
    bulletColor: 0xffffff,
    bulletSize: 3,
    shotPattern: 'none',
    fireInterval: 1000,
    bulletSpeed: 50,
    bulletLifetime: 1.5,
    burstCount: 1,
    shotProbability: 0,
  },
  'ghost-flank': {
    key: 'ghost-flank',
    displayName: 'Ghost (Flank)',
    formationKind: 'single',
    count: 1,
    spacingX: 0,
    spacingY: 0,
    driftSpeed: 0,
    startX: GAME_WIDTH * 0.5,
    startY: GAME_HEIGHT * 0.25,
    startXMin: GAME_WIDTH * 0.5,
    startXMax: GAME_WIDTH * 0.5,
    startYMin: GAME_HEIGHT * 0.25,
    startYMax: GAME_HEIGHT * 0.25,
    size: 16,
    health: 1,
    color: 0x22ffff,
    bulletColor: 0xffffff,
    bulletSize: 3,
    shotPattern: 'none',
    fireInterval: 1000,
    bulletSpeed: 50,
    bulletLifetime: 1.5,
    burstCount: 1,
    shotProbability: 0,
  },
  'ghost-wander': {
    key: 'ghost-wander',
    displayName: 'Ghost (Wander)',
    formationKind: 'single',
    count: 1,
    spacingX: 0,
    spacingY: 0,
    driftSpeed: 0,
    startX: GAME_WIDTH * 0.5,
    startY: GAME_HEIGHT * 0.25,
    startXMin: GAME_WIDTH * 0.5,
    startXMax: GAME_WIDTH * 0.5,
    startYMin: GAME_HEIGHT * 0.25,
    startYMax: GAME_HEIGHT * 0.25,
    size: 16,
    health: 1,
    color: 0xffb852,
    bulletColor: 0xffffff,
    bulletSize: 3,
    shotPattern: 'none',
    fireInterval: 1000,
    bulletSpeed: 50,
    bulletLifetime: 1.5,
    burstCount: 1,
    shotProbability: 0,
  },
  // Defender patrol-and-attack raider (AH-0MV01EM7U0033W7L): a fast single
  // actor that sweeps the arena in a horizontal patrol, commits to a
  // straight high-speed attack run toward the player's snapshotted position,
  // overshoots and wraps back into patrol. `driftSpeed` is the patrol speed,
  // `attackSpeed` the committed run speed and `commitRange` the proximity
  // that triggers a commit (see `docs/CLASSIC_ENEMY_RESEARCH.md` §6). Health
  // 2 so it survives one hit and demands a committed read.
  raider: {
    key: 'raider',
    displayName: 'Raider',
    formationKind: 'single',
    count: 1,
    spacingX: 0,
    spacingY: 0,
    driftSpeed: 140,
    attackSpeed: 320,
    commitRange: 260,
    startX: GAME_WIDTH * 0.5,
    startY: GAME_HEIGHT * 0.25,
    startXMin: GAME_WIDTH * 0.5,
    startXMax: GAME_WIDTH * 0.5,
    startYMin: GAME_HEIGHT * 0.25,
    startYMax: GAME_HEIGHT * 0.25,
    size: 18,
    health: 2,
    color: 0xff4433,
    bulletColor: 0xffddaa,
    bulletSize: 3,
    shotPattern: 'aimed',
    fireInterval: 1100,
    bulletSpeed: 110,
    bulletLifetime: 1.4,
    burstCount: 1,
    shotProbability: 0.6,
  },
  harvester: {
    key: 'harvester',
    displayName: 'Harvester',
    formationKind: 'single',
    count: 1,
    spacingX: 0,
    spacingY: 0,
    driftSpeed: 0,
    startX: GAME_WIDTH * 0.5,
    startY: GAME_HEIGHT * 0.25,
    startXMin: GAME_WIDTH * 0.5,
    startXMax: GAME_WIDTH * 0.5,
    startYMin: GAME_HEIGHT * 0.25,
    startYMax: GAME_HEIGHT * 0.25,
    size: 44,
    health: 5,
    color: 0x9b30ff,
    bulletColor: 0xcc88ff,
    bulletSize: 3,
    shotPattern: 'none',
    fireInterval: 1000,
    bulletSpeed: 50,
    bulletLifetime: 1.5,
    burstCount: 1,
    shotProbability: 1.0,
  },
};

export const DEFAULT_ENEMY_KEYS = Object.keys(DEFAULT_ENEMY_CONFIGS);

/** Built-in ship defaults — sourced from the leaf `constants.ts` values. */
export const DEFAULT_CONFIG: ShipConfig = {
  thrustAcceleration: THRUST_ACCELERATION,
  maxSpeed: MAX_SPEED,
  shipSize: SHIP_SIZE,
  thrustFlameLength: THRUST_FLAME_LENGTH,
  shipColor: SHIP_COLOR,
  thrustFlameColor: THRUST_FLAME_COLOR,
  thrustFlameInnerColor: THRUST_FLAME_INNER_COLOR,
  frictionDeceleration: FRICTION_DECELERATION,
  controlScheme: 'asteroids',
  asteroidsRotationSpeed: 3,
  asteroidsRotationAcceleration: 12,
  asteroidsRotationDeceleration: 60,
};
